### ISSUE TITLE
Input maker to read one request body per document

### ISSUE THREAD

**Issue by Gabrielgtt** [vtex/reliability-research#111]
The `input_maker` will need a different format for reading request bodies: one folder with one document per body. 
This is better for debugging and code efficiency (memory-wise).
The `--body_file` param will now be a `--body_folder`

Three important action points:
- Change our load file from a _single document_ to _one document per body_
- Change `input_maker` to support this new format
- Change documentation

**Comment by paulofelipefeitosa** [comment]
Hi everyone, specially @danielfireman. I and @Gabrielgtt already discussed an initial version of the new experiment setup workflow. 

We wrote an initial [specification draft](https://docs.google.com/document/d/1VVGNzDasNFgqlfSU777bzwLjKUx84mXKb4UURQtf9Tc/edit?usp=sharing), we plan to improve the specification description and draw the new workflow diagram to comment it here, then present and discuss it at our Monday sync.

**Comment by danielfireman** [comment]
Cool stuff. Like where this is heading to! Sent some comments in the spec doc.

**Comment by Gabrielgtt** [comment]
Updates: You can see our design for load preprocessing all the way to replaying the load in [this diagram](https://drive.google.com/open?id=1YevJECCGQJRGVQG6ng-sDKJ9q6dFDomM)
Notice that there is one tab for each component: `input_maker`, `batcher` and `replayer`!

As usual, all PRs will link this issue to keep it updated

**Comment by paulofelipefeitosa** [comment]
Hi everyone, specially @danielfireman and @thiagomanel, we already tested the new experiment setup workflow and the new Replayer component with the canonical load, everything appears to be working well. 
Now we are adding the new components documentation to be easy to use and understand them. After this step, we intend to open a PR into master and start to work in issue #97.

**Comment by paulofelipefeitosa** [comment]
Friendly ping on this @danielfireman @thiagomanel

**Comment by Gabrielgtt** [comment]
As our work here is done, future problems will be discussed in other issues
