### ISSUE TITLE
Improve metrics logs collector documentation

### ISSUE THREAD

**Issue by gugabribeiro** [vtex/reliability-research#130]
The metrics logs collector do not describe the meaning of the values collected very well. 

Column | Meaning | Type
-- | -- | --
type | Type of garbage collect | String
stopped_threads_time | Duration where threads spent stopped | milliseconds
timestamp | Timestamp of this measurement | HH:MM:SS

- Does the `timestamp` the time of the measurement or the time where the garbage collector started running? 
- Does the `stopped_threads_time` be the total time of the garbage collector threads in idle or of the application itself?

**Comment by gabialverga** [comment]
The stop_threads_time is the break time for the evacuation of the regions to end.
