### ISSUE TITLE
Create a script to start and configure a cluster from scratch

### ISSUE THREAD

**Issue by gugabribeiro** [vtex/reliability-research#132]
In order to save resources used by the project, we need to be able to start and configure a cluster from scratch automatically whenever we need to.

The start-up includes:
- Launch the Cluster VMs

The configuration includes:
- Install SOLR in production mode
- Copy the index to the SOLR data folders

**Comment by igornatanael** [comment]
Hi, @gugabribeiro. Could you describe a little bit better the actions, specially how is the will be the process to copy SOLR index to the data folders
