### ISSUE TITLE
Timestamp default format

### ISSUE THREAD

**Issue by dfquaresma** [vtex/reliability-research#138]
Some tools used in experiments provide timestamp data as output. This issue suggests that we may use a default format for the timestamp of all used tools. The chosen default format is the monotonic timestamp in nanoseconds.

## Current Behavior

Metrics and Replayer are two used tools which provide the timestamp in their output files but in different formats.  The current Replayed implementation is using the UTC pattern and the Matrics uses epochs.

## Possible Solution

Updatements at Replayer around line [173](https://github.com/vtex/reliability-research/blob/master/replayer/main.go#L173), Metrics Collector around the line [178](https://github.com/vtex/reliability-research/blob/master/metrics/metrics_collector.py#L178) and [186](https://github.com/vtex/reliability-research/blob/master/metrics/metrics_collector.py#L186), and Logs Collector around the line [55](https://github.com/vtex/reliability-research/blob/master/metrics/logs_collector/lc_functions.py#L55).

## Context

During the results evaluation phase, those timestamp values should be in the same format to easier the treatment of this variable in analysis scripts.

**Comment by Gabrielgtt** [comment]
Hi @dfquaresma, nice suggestion!
We currently have to collect metrics from a cluster of Solr instances and to synchronize their clocks we should use Real-Time Timestamps, but depending on the experiment is better to have indeed a monotonic timestamp. I may be wrong tho, what do you think about it?
My suggestion is to allow our metrics collector to collect the monotonic, the real-time timestamps, or both.

**Comment by dfquaresma** [comment]
> Hi @dfquaresma, nice suggestion!
> We currently have to collect metrics from a cluster of Solr instances and to synchronize their clocks we should use Real-Time Timestamps, but depending on the experiment is better to have indeed a monotonic timestamp. I may be wrong tho, what do you think about it?
> My suggestion is to allow our metrics collector to collect the monotonic, the real-time timestamps, or both.

I agree with you.
