### ISSUE TITLE
Number of metrics results does not match expectations

### ISSUE THREAD

**Issue by gabialverga** [vtex/reliability-research#139]
It was noticed that the Metrics' output is not consistent. The number of measurements isn't the expected one.

## Expected Behavior
The number of measurements in Metrics' output should be greater (because Metrics starts first) to the experiment's duration in milliseconds divided by the Metrics' tick_rate param to each Solr instances.

## Current Behavior
The number of responses obtained by the metrics was below the expected quantity. We observed it during experiments performed with Solr Cloud. Considering that our experiments take 4 minutes and the tick_rate was of 1 second, we expected to have ~960 lines (4 Solr instances x 240.000 milliseconds / 1000 milliseconds of tick_rate) in the output files of metrics_collector but the output files have only ~320 lines.

**Comment by dfquaresma** [comment]
We discover that the problem was that the SCP calls were delaying each measurement collection. When removed, all measurements matched with the expected. A was of solving is simple to move this measurement save into the Solr instances and retrieve those data afterward the experiments.
