### ISSUE TITLE
Creation of tests for metric collectors.

### ISSUE THREAD

**Issue by gabialverga** [vtex/reliability-research#150]
## Expected behavior
The creation of test scripts for the entire metrics collection tool, currently only one logs_collector has tests created. We need metrics_collector tests should be created, In order to increase their reliability too.
## Current behavior
Currently there is only one simple test for logs_collector that checks if it is not in the correct format.

## Possible solution
An improvement of the test script for logs_collector and creation of scripts for testing metrics_collector must be performed.

**Comment by gabialverga** [comment]
In the logs_collector there would be a documentation improvement, explaining what is tested and how to run it. The same would be done in metrics_collector, creating the tests together with documentation.

**Comment by danielfireman** [comment]
@gabialverga ... what **exactly** did you mean by `more complete test scripts for the metrics measurement tools`? Please, edit the description making it more descriptive.
