### ISSUE TITLE
Remove Avgload Collector from Metrics

### ISSUE THREAD

**Issue by dfquaresma** [vtex/reliability-research#151]
We still have a bug in a component of Metrics. That bug occurs as described further ahead in this issue, but I would like to enumerate some reasons why we shouldn't solve this problem, but instead, we should remove that feature from metrics.

- The avgload collector is a component of Metrics used only to a specific end: provide avg load metric to the experiment described at #100. Since that analysis was aborted, we have no use to it anymore (at least for now).
- We yet do not know the reason why this bug is occurring and consequently, we have no solution yet. If we want to solve it, we shall invest time in this task. Since we must focus on implement tests right know (as described at #150)
- Since we have cited #150, I must also say that remove the avgload collector component would reduce the number of tests we should add and consequently reduce the time spent improving/adding tests.
- The avgload collector contributes negatively to the Metrics architecture design. Since it must run in each Solr instance, it must be copied to each instance every time we start the cluster. Not only that, but this component is also controlled remotely what requires more attention since if the command fails we lose the experiment.
- Still talking about design, the distributed design also makes things hard to analyze once the timestamps of each measurement may differ from each other. With the periodical components of metrics centralized, it could not be a problem.
- Finally, the last point. In the future, I think we may start to use Cloud Watch for some metrics. Once invested time enough to provide the use of Cloud Watch automatically, this metric may be retrieved through this new method.
 
## Expected Behavior

It should run through all the experiments and have a number of measurements closer to the number we calculate considering the tick rate and the experiment duration, as described at #139.

## Current Behavior

The number of measurements does not match the expected. Running it alone, without the experiment context, it looks like was working properly. However, when we run it with the experiment it seems to crash after some seconds.

## Possible Solution

Since we can remove it without losses, we should remove it due to the reasons mentioned. 
To remove it, we must do the following steps:
- Delete the [avgload collector file](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/avgload_collector.py)
- Remove this ["for loop"](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/metrics_collector.py#L142) and this [function](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/metrics_collector.py#L156)
- Remove [this](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/logs_collector/logs_collector.py#L42) and the following lines in this [file](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/logs_collector/logs_collector.py).
- Finally, remove it from readme docs [here](https://github.com/vtex/reliability-research/blob/84135c7ac81bd3539a9f199239630b79ab9928a3/metrics/README.md#avgloadcsv).

## Steps to Reproduce (for bugs)

1. Start the cluster of VMs using the [cluster script ](https://github.com/vtex/reliability-research/tree/master/cluster#cluster-scripts) and another VM to run the Replayer/Metrics.
2. Copy avgload_metrics.py to each Solr VM instance.
3. Perform an experiment as described [here](https://github.com/vtex/reliability-research/blob/master/PLAYBOOK.md)
4. Check if the number of measurements matches with the expected described [here](https://github.com/vtex/reliability-research/issues/139).

## Context

During our experiment phase, we realized that our tool to retrieve the metrics we need had a bug. It seems to stop running after a period and so that it doesn't collect the metrics during the experiment. Said so, that bug in avgload collector makes it useless.

**Comment by igornatanael** [comment]
Congrats, @dfquaresma. It is really well written. I agree with your points, just would to know:

- is it easy to create a way to make possible to enable/disable this metric collection? as you said in one of your points, we do not need this for now, but we can need it in a near future and until we do not find a better way to do it and implement (as cloudwatch metric), we need to have like a backup as an option ready (or almost, at least)

do you think it makes sense?

**Comment by dfquaresma** [comment]
> Congrats, @dfquaresma. It is really well written. I agree with your points, just would to know:
> 
> * is it easy to create a way to make possible to enable/disable this metric collection? as you said in one of your points, we do not need this for now, but we can need it in a near future and until we do not find a better way to do it and implement (as cloudwatch metric), we need to have like a backup as an option ready (or almost, at least)
> 
> do you think it makes sense?

I don't think we may need it in the near future. I also don't know if start to use the Cloud Watch will demand more time to implement all the requirements than fixing the current bug in the avgload collector.

Allow a enable/disable would fix for now some of the problems I've pointed, but the other (such as the design concerns) will remain. I think that if we want to keep with this metric we should rethink how to retrieve it. However, again, I don't think we may need it in the near future.

**Comment by igornatanael** [comment]
Ok. Trust in your feeling.
Can do it! 
One thing more: remove it already make the design changes? If it needs something else, please edit the description and explain better what it will demand

**Comment by dfquaresma** [comment]
> Ok. Trust in your feeling.
> Can do it!
> One thing more: remove it already make the design changes? If it needs something else, please edit the description and explain better what it will demand

Yes. The only distributed component in Metrics is the avgload collector. Removing it allows running Metrics centralized. I'll update the possible solution section in description explaining how to do it and open a PR doing so.

**Comment by igornatanael** [comment]
Ok, perfect. Go ahead, @dfquaresma!
