### ISSUE TITLE
[Execution] Run Load Test With Canonical Load

### ISSUE THREAD

**Issue by danielfireman** [vtex/reliability-research#95]
Anyone in our project should be able to run the load test we are currently working on. That means:
- Bring up the production-like environment with SOLR instances and Zookeper instances (same machine, same SOLR configuration, same JVM)
- Load the indexes of each SOLR instance
- **No NGINX**: the replayer will send requests to SOLR instances in round-robin
- Run the replayer, reproducing the production load (same batch size, same inter arrival time)

To consider this issue accomplished, besides running the experiment, we should have a playbook. The playbook will teach teach each step to run a load test (starting from logging into AWS). @LiviaCavalcanti will be responsible for this issue and @gugabribeiro will be consulting on the environment setup. Both should work together on the playbook. 

## Verification

@thiagomanel will follow the playbook and run an experiment :smiley:

**Comment by igornatanael** [comment]
As soon as we already ran the canonical load, maybe we could already close this issue, right @Gabrielgtt?

**Comment by Gabrielgtt** [comment]
I don't know if @thiagomanel and @danielfireman ran a test as the Verification suggests, but besides that, I think we can close it out
