### ISSUE TITLE
[Execution] Evaluate replayer quality

### ISSUE THREAD

**Issue by danielfireman** [vtex/reliability-research#97]
This issue aims to answer the following question: is the replayer replaying the load properly?

You have a description of the inter arrival times (what needs to be replayed) and believe the replayer don't output the timestamp of each request (please double check). So, currently you don't even have a way to perform the inter-arrival evaluation. Furthermore, the requests being issued match with what needs to be issued? To the former, a plain statistical (graphical) analysis is enough. To the latter, a regression test.

## Reminder
First thing to do is to describe a plan of action:
- About the inter-arrival times? what exactly are you going to check? How? Any ideas of which stats to show?
- About the request content, how are you planning to do the regression test? 
    - Pro-Tip: as the output should be deterministic, use a hand-crafted golden file and simply compare. If it fails, show a diff.

## Verification

@danielfireman will review the regression test and @Gabrielgtt will do a 5 minute presentation about his findings

**Comment by paulofelipefeitosa** [comment]
Working on it, I want to deliver a script that can analyze the Replayer output quality by responding to whether the Replayer is triggering the request as close as to the expected triggering time.

**Comment by Gabrielgtt** [comment]
As #111 shows, we've fixed the problems with the load shape. 
We've made [an analysis of our experiment](https://docs.google.com/document/d/1nRD5Md-ukyTJ13DMSM8l5wPSG4jvPcPlKCVB0iG3PS4/edit) with the canonical load and have interesting results about future changes to the Replayer. Please, check it out!

/cc @danielfireman @igornatanael @thiagomanel
