### ISSUE TITLE
[Analysis] Impact of the GC

### ISSUE THREAD

**Issue by danielfireman** [vtex/reliability-research#99]
After running an experiment and collecting metrics, one thing we need is to understand how the GC impacts the response time.

## Reminder
First things to do

1. **Read about correlation and read the paper we published at CloudCom 2018**: this will give ideas about what to look for and how to present the impact. 
    - Pro-Tip: Look at the histogram tail, mean and median might not show much
1. Describe a plan of action: what are you going to look? How? Any idea about the stats?

## Verification

A 7 minute presentation about the results

**Comment by LiviaCavalcanti** [comment]
Hi, @danielfireman , me and @gugabribeiro we were thinking about the following scenario:
- Investigate how much the heap size impacts the requests response time.
- The hypothesis is that there is a negative correlation between them, that means, the smaller the heap size, the greater the correlation of response time
- The workload to be used is two files: one for POST and another one for GET, both derived from the canonical workload.
- Besides that, the heap size will vary between the values [512M, 4G, 16G]. 
- The analysis will be made on the response time percentiles variations. Plotting ECDF. Calculate the correlation between response time and heap size. Counting the garbage collections frequency, too.

**Comment by danielfireman** [comment]
Let's simplify and clarify a bit:

- 1-Factor Experiment: Heap Size (512M, 4G, 16G)
- 2 Dependent Variables (which you will look into correlation): GC Count (or GC time), Response Time

The workload could be the 1/4 downsampled replay input, which you can run today. The SOLR configuration will need to change due to the heap size.

**Comment by LiviaCavalcanti** [comment]
| | 2GB | 6GB | 16GB|
|:------------------:|:------------------:|:------------------:|:------------------:|
Number of GC | 810 | 2226 | 2240
Minimum Time Threads Times | 0.0140 | 0.015 | 0.016
1st  Quartil Time Threads Times | 0.23 | 0.03 | 0.036
Median Time Threads Times | 0.026 | 0.033 | 0.04
3st  Quartil Time Threads Times| 0.3 | 0.04 | 0.044
Max Time Threads Times | 0.081 | 0.14 | 0.14

**Comment by danielfireman** [comment]
Report can be found at: https://docs.google.com/document/d/12kyFK3wy0KTX-kw98uGcMWnCqyh2Q1Z_ft3njiCuXck/edit?usp=sharing
